### GET ALL
GET http://127.0.0.1:8080/v1/item/get HTTP/1.1

### CREATE
POST http://127.0.0.1:8080/v1/item/create/rest HTTP/1.1


### EDIT
POST http://127.0.0.1:8080/v1/item/edit HTTP/1.1
content-type: application/json

{
    "title": "learn",
    "status": "Done"
}

### CREATE USER
POST http://127.0.0.1:8080/v1/user/create HTTP/1.1
content-type: application/json

{
    "name": "user1",
    "email": "user1@mail.com",
    "password": "password"
}